config/routes.rb
WowApp::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "Giris", sign_out: "Cikis"} 
  resources :wonders, only: [:new, :create, :destroy, :show, :update, :index]
  resources :comments, only: [:create, :destroy]
  resources :travels, only: [:create, :destroy, :show, :update, :index]
  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'

end

app/models/best_tag.rb
class BestTag < ActiveRecord::Base
  belongs_to :wonder_type
  belongs_to :property_tag
end

app/models/checkpoint.rb
class Checkpoint < ActiveRecord::Base
  belongs_to :travel
  belongs_to :wonder
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :commentable, :polymorphic => true
	default_scope -> { order('created_at DESC') }
	validates :user_id, presence: true
end

app/models/property_tag.rb
class PropertyTag < ActiveRecord::Base
	has_many :best_tags
	has_many :wonder_types, through: :best_tags
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :wonder
  validates :user_id, :wonder_id, presence: true
end

app/models/route.rb
class Route < ActiveRecord::Base
	belongs_to :user
	has_many :comments, as: :commentable
	has_many :checkpoints
end

app/models/travel.rb
class Route < ActiveRecord::Base
	belongs_to :user
	has_many :comments, as: :commentable
	has_many :checkpoints
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :wonders
	has_many :comments, dependent: :destroy
	has_many :ratings, dependent: :destroy
	has_many :travels, dependent: :destroy
  	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/wonder.rb
class Wonder < ActiveRecord::Base
	belongs_to :user
	has_many :comments, :as => :commentable
	has_many :ratings, dependent: :destroy
	belongs_to :wonder_type
	default_scope -> { order('created_at DESC') }
	validates :user_id, presence: true

	include PgSearch
 	pg_search_scope :search, against: [:name]

	def self.text_search(query)
		if query.present?
			search(query)
		else
			scoped
		end
	end
end

app/models/wonder_type.rb
class WonderType < ActiveRecord::Base
	has_many :wonders
	has_many :best_tags
	has_many :property_tags, through: :best_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!, only: [:create, :destroy]
	
	def create
		@comment = current_user.comments.build(comment_params)
		if @comment.save
	    	flash[:success] = "Yorum eklendi!"
	    else
	    	flash[:error] = "Yorum kaydedilmedi!"
	    end
	    redirect_to(Wonder.find(@comment.commentable_id))
	end

	def destroy
	end

	private

	    def comment_params
	    	params.require(:comment).permit(:content, :commentable_id, :commentable_type)
	    end
end

app/controllers/routes_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!, only: [:create, :destroy, :update]

	def new
	end

	def create
	end

	def destroy
	end

	def show
	end

	def update
	end

	def index
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@wonders = Wonder.order("RANDOM()").limit(3)
  end

  def help
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
	before_action :authenticate_user!, only: [:create, :destroy, :update]

	def new
	end

	def create
	end

	def destroy
	end

	def show
	end

	def update
	end

	def index
	end
end

app/controllers/wonders_controller.rb
class WondersController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy, :update]
  
  def index
    @wonders = Wonder.text_search(params[:query]).page(params[:page]).per_page(20)
  end

  def new
    @propertyTags = PropertyTag.all
    @wonder = Wonder.new
    @wonders = Wonder.all
  end

  def create
  	@wonder = Wonder.new(wonder_params)
    @wonder.user_id = current_user.id
    if @wonder.save
      flash[:success] = "Harika eklendi!"
      redirect_to(@wonder)
    else
      render 'static_pages/home'
    end
  end

  def show
    @wonders = Wonder.order("RANDOM()").limit(10)
    @wonder = Wonder.find(params[:id])
    @comments = @wonder.comments.paginate(page: params[:page])
    @comment = current_user.comments.build if signed_in?
  end

  def update
    @wonder = Wonder.find(params[:id])
    @wonder.update_attributes(wonder_params)
    redirect_to @wonder
  end

  def destroy
  end

  private

    def wonder_params
      params.require(:wonder).permit(:name, :lat, :lng).tap do |whitelisted|
        whitelisted[:properties] = params[:wonder][:properties] 
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "WondersOfTheWorld"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar (http://gravatar.com/) for the given user.
	def gravatar_for(user, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.email, class: "gravatar")
	end

end

app/views/comments/_comment.html.erb
<li>
	<%= link_to gravatar_for(comment.user), wonders_path, class: 'commentGravatar' %>
	<span class="content"><%= comment.content %></span>
	<span class="timestamp">
		<%= comment.created_at %>
	</span>
</li>

app/views/layouts/_footer.html.erb
<footer class="footer container-fluid">
  <div class="row footerFirstRow">
    <div class="col-md-41"></div>
  </div>
  <div class="footerCenter row">
    <ul class="col-md-6 col-md-offset-9">
      <li>Anasayfa</li>
      <li>Harikalar</li>
      <li>Rotalar</li>
      <li>Uzman Sayfaları</li>
    </ul>
    <ul class='col-md-6'>
      <li><%= link_to "Hakkında", '#' %></li>
      <li><%= link_to "İletişim", '#' %></li>
      <li><%= link_to "Haberler", '#' %></li>
      <li><%= link_to "Yardım", '#' %></li>
      <li><%= link_to "Kullanım Koşulları", '#' %></li>
    </ul>
    <ul class='col-md-6'>
      <li><%= link_to "Kaydol", '#' %></li>
      <li><%= link_to "Giriş", '#' %></li>
      <li><%= link_to "Düzenle", '#' %></li>
    </ul>
    <ul class='col-md-6'>
      <%= form_tag wonders_path, method: :get do %>
        <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Bul" %>
      <% end %>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
  <div class="container navbar-wrapper">
    <div class="navbar navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to image_tag("logo2.png", alt: "wonderroute"), root_path, id: "logo", class: "navbar-brand" %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= gravatar_for(current_user, size:40) %></li>
              <li><%= link_to current_user.email, edit_user_registration_path, class: "userEmail" %></li>
              <li><%= link_to 'Çıkış', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Kayıt ol', new_user_registration_path %></li>
              <li><%= link_to "Giriş", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="tabsBar">
    <ul class="navbarBelow">
      <li><%= link_to "Anasayfa", root_path %></li>
      <li><%= link_to "Harikalar", wonders_path %></li>
      <li><%= link_to "Yeni Harika Ekle", new_wonder_path %></li>
      <li><%= link_to "Rotalar", travels_path %></li>
      <li><%= link_to "Yardım",    '#' %></li>
    </ul>
  </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
#encoding: utf-8
<!DOCTYPE html>
<html>
<head>
  <link href="http://fonts.googleapis.com/css?family=Roboto&subset=latin,latin-ext" rel="stylesheet" type="text/css">
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link  href="http://fotorama.s3.amazonaws.com/4.6.2/fotorama.css" rel="stylesheet"> <!-- 3 KB -->
  <script type="text/javascript" src="http://www.panoramio.com/wapi/wapi.js?v=1&amp"></script>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container-fluid">
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/shared/_comment_form.html.erb
<%= form_for(@comment) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_area :content, placeholder: "Yorum giriniz...", rows: 4 %>
		<%= f.hidden_field(:commentable_id, :value => @wonder.id) %>
    <%= f.hidden_field(:commentable_type, :value => 'Wonder') %>
	</div>
	<%= f.submit "Gönder", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_properties_form.html.erb
<%= form_for(@wonder) do |f| %>
  <div class='attributeContainer'>
    <div class='row attributeTemplate <%= 'hide' if @wonder.properties.present? %>'>
      <p class='col-md-3'>
        <input class='text_field dynamicAttributeName' id='' name='' placeholder='Yeni Özellik İsmi' size='15' type='text' />
      </p>
      <p class='col-md-3'>
        <input class='text_field' id='bar' name='' placeholder='Değer' size='15'  type='text'  />
      </p>
      <p class='col-md-1'>
        <a herf='#' class='btn removeRow'>X</a>
      </p>
    </div>
    <%= link_to '#', :class => 'addAttribute' do %>
      <span class='glyphicon glyphicon-plus' aria-hidden='true'></span>Yeni Özellik Ekle
    <% end %>
  </div>

  <div class="form-actions">
    <div class='showFormButtons hide'>
      <%= f.submit 'Kaydet', class: 'btn primary' %> ya da
      <%= link_to "İptal", request.referrer || wonder_path %>
    </div>
  </div>
<% end %>

app/views/shared/_ratings_form.html.erb
<%= form_for(@wonder) do |f| %>
  <div>ss</div>
<% end %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Anasayfa') %>
<div id='homeFoto'></div>
<div class="searchForm">
	<p>Dünyanın harikalarını keşfedin</p>
	<%= form_tag wonders_path, method: :get do %>
		<%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Bul..." %>
	<% end %>
</div>
<div class='container pageCon'>
  <div class='row'>
    <h3 class='homeHeaders'>Harikalar</h3>
  </div>
  <div class='row'>
    <div class='col-md-13'><div class='wonderPhotos1'></div><p class='fotoExp'>Eiffel Kulesi</p></div>
    <div class='col-md-13 col-md-offset-1'><div class='wonderPhotos2'></div><p class='fotoExp'>Golden Gate Köprüsü</p></div>
    <div class='col-md-13 col-md-offset-1'><div class='wonderPhotos3'></div><p class='fotoExp'>Orient Pearl Kulesi</p></div>
  </div>
  <div class='row'>
    <h3 class='homeHeaders'>Ülkelere Göre Bul</h3>
  </div>
  <div class='row'>
    <div class='col-md-13'><div class='wonderPhotos4'></div><p class='fotoExp'>Türkiye</p></div>
    <div class='col-md-13 col-md-offset-1'><div class='wonderPhotos5'></div><p class='fotoExp'>Yunanistan</p></div>
    <div class='col-md-13 col-md-offset-1'><div class='wonderPhotos6'></div><p class='fotoExp'>ABD</p></div>
  </div>
</div>

app/views/travels/index.html.erb
<% provide(:title, 'Rotalar') %>
<div class="container routeIndexCon">
  <div><a href="#" data-toggle="modal" data-target="#addRoute-modal-lg">Yeni rota ekleyin</a></div>
  <div class="modal fade" id="addRoute-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Kapat</span></button>
          <h4 class="modal-title" id="myModalLabel">Rota Ekleyin</h4>
        </div>
        <div class="modal-body">
          <div class="map" id="routeNewMap">
            <div id="map-canvas"></div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Kapat</button>
          <button type="button" class="btn btn-primary">Kaydet</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/wonders/_wonder.html.erb
<%= hidden_field_tag wonder.name wonder.id data: {lat: wonder.lat, lng: wonder.lng} %>

app/views/wonders/index.html.erb
<% provide(:title, 'Harikalar') %>
<div class="container" id="wonders">
  <% @wonders.each do |w| %>
  	<div class="indexWonder">
    	<h2>
      	<%= link_to w.name, w %>
      	<span class="comments">(<%= w.comments.size %> yorum)</span>
    	</h2>
    </div>
  <% end %>
</div>
<%= will_paginate @wonders %>

app/views/wonders/new.html.erb
<% provide(:title, 'Dünyanın harikaları') %>
<div class="container pageCon">
	<div class='map' id='createMap'>
		<div id='map-canvas'></div>
		<% @wonders.each do |wonder| %>
			<input type='hidden' data-name="<%= wonder.name %>" data-lat=<%= wonder.lat %> data-lng=<%= wonder.lng %> >
		<% end %>
	</div>
</div>
<div class="container">
	<div id='formDiv' class="row">
		<div class="col-md-25 col-md-offset-6">
			<%= form_for(@wonder) do |f| %>
			  <div class="recomProp">
			  	<div class="row">
			  		<div class="col-md-15"><p class="propHeader">Ara: </p></div>
			  		<div class="col-md-26"><input id="pac-input" class="controls" type="text" placeholder="Ara..."></div>
			  	</div>
			  	<div class="row">
			  		<div class="col-md-15"><p class="propHeader">Harika İsmi: </p></div>
			  		<div class="col-md-26"><%= f.text_area(:name, placeholder: "İsim giriniz...") %></div>
			  	</div>
			  	<div class="row">
			  		<div class="col-md-15"><p class="propHeader">Harika Türü: </p></div>
			  		<div class="col-md-26"><%= collection_select(:wonder, :wonder_type_id, WonderType.all, :id, :name) %></div>
			  	</div>
				  <% @propertyTags.each do |p| %>
				  	<div class="row property hide">
				  		<div class="col-md-15"><p class="propHeader"><%= p.name %> : </p></div>
				  		<div class="col-md-26"><input class="text_field dynamicAttributeName" id="<%= 'wonder_properties_' + p.name %>" name="<%= 'wonder[properties][' + p.name + ']' %>" data-wtypes="<%= p.wonder_types.map{|c| c.name}.map(&:inspect).join(',') %>" placeholder="<%= p.name %> için değer..." type="text" ></div>
			  		</div>
			  	<% end %>
			  </div>
			  <%= f.hidden_field(:lat, :value => "") %>
			  <%= f.hidden_field(:lng, :value => "") %>
			  <%= f.submit "Ekle", class: "btn btn-large btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/wonders/show.html.erb
<% provide(:title, 'Dünyanın harikaları') %>
<div class='container pageCon' >
	<div class='row'>
		<div class='col-md-41'>
			<h1><%= image_tag 'pisa.png', alt:'wonderStamp' %> <%= @wonder.name %></h1>
		</div>
	</div>
	<div class='row'>
		<div class='col-md-13'>
			<% if @wonder.properties.present? %>
				<ul>
				<% @wonder.properties.each do |key, value| %>
					<li class='showProp'><span class='showPropKey'><%= key %>:</span> <%= value %></li>
				<% end %>
				</ul>
			<% end %>
			<% if signed_in? %>
				<%= render 'shared/ratings_form' %>
				<%= render 'shared/properties_form' %>
			<% end %>
		</div>
		<div class='col-md-13 col-md-offset-1' id='wonderChoosen'>
			<input type='hidden' data-name="<%= @wonder.name %>" data-lat=<%= @wonder.lat %> data-lng=<%= @wonder.lng %> >
			<div class='foto' id='wapiblock'></div>
		</div>
		<div class='col-md-13  col-md-offset-1 map' id='showMap'>
			<div id='map-canvas'></div>
		</div>
	</div>
	<hr>
	<div class='row'>
		<div class='col-md-30' id='commentDiv'>
			<% if signed_in? %>
				<%= render 'shared/comment_form' %>
			<% end %>
			<% if @wonder.comments.any? %>
				<h3>Yorumlar (<%= @wonder.comments.count %>)</h3>
				<ol class="showComment">
					<%= render @comments %>
				</ol>
				<%= will_paginate @comments, :previous_label => 'Önceki', :next_label => 'Sonraki' %>
			<% end %>
		</div>
		<div class='col-md-3' id='showSidebar'>
			<% @wonders.each do |wonder| %>
				<div>
					<span><%= wonder.name %></span>
				</div>
			<% end %>
		</div>
	</div>
</div>